name: Build from Maven and push to WireMock Cloud

on:
  push:
    branches:
      - 'main'

jobs:
  build_and_push:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Run
        env:
          WIREMOCK_API_TOKEN: ${{ secrets.WIREMOCK_API_TOKEN }}
          MOCK_API_ID: ${{ env.MOCK_API_ID }}
        run: (cd maven && bash -x ./push-to-wmc.sh)